# Generated by Django 3.1.6 on 2021-03-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210331_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
