# Generated by Django 3.1.6 on 2021-03-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210331_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quintile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contains', to='website.quintile'),
        ),
    ]
