# Generated by Django 3.1.6 on 2021-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210331_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quintile',
            name='quintile',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
