# Generated by Django 3.1.6 on 2021-03-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210331_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
